/* 
Number guessing game in java.
1. Generate a random number within a specified range, such as 1 to 100
2. Prompt the user to enter their guess for the generated number.
3.  Compare the user's guess with the generated number and provide
    feedback on whether the guess is correct, too high, or too low
4. Repeat steps 2 and 3 until the user guesses the correct number.
You can incorporate additional details as follows:
5. Limit the number of attempts the user has to guess the number.
6. Add the option for multiple rounds, allowing the user to play again.
7. Display the user's score, which can be based on the number of attempts taken or rounds won.
*/

import java.util.Random;
import java.util.Scanner;

public class NumGuessGame{
    public static void main(String[] args) {
        // Create a instance for random class
        Random random = new Random();
        // Create a instance for scanner class
        Scanner scan = new Scanner(System.in);

        System.out.println("Computer generated random number b/w (1-100): ");

        int randomNumber = random.nextInt(100) + 1;
        // System.out.println(randomNumber);

        int tryCount = 0;

        while (true) {        

        // Prompt the user to enter their guess for the generated number
        System.out.println("Now enter your guess for the random number generated by computer: ");
        int userGuess = scan.nextInt();

        tryCount ++;

        // Compare the user's guess with the generated number and provide
        // feedback on whether the guess is correct, too high, or too low

        if(randomNumber == userGuess){
            System.out.println("Your guess is correct! You win!");
            System.out.println("score out of 10, -1 for each attempt you took");
            System.out.println("It took " + tryCount + " tries");
            int score = 10 - tryCount;

            if(score < 0){
                System.out.println("your score is 0 / 10");
            }
            else if(score == 9){
                System.out.println("Your score is 10 / 10");
            }
            else{
                System.out.println("Your score: " + score + "/10");
            }

            break;
        }

        else if(randomNumber > userGuess){
            System.out.println("Your guess number is lower guess again.");
        }

        else if(randomNumber < userGuess){
            System.out.println("Your guess number is Heigher guess again.");
        }
       
        
        }
        // Closing scan
        scan.close();
    }

}